import { createSlice } from "@reduxjs/toolkit";
import { fetchUsers } from "./users.thunk";

const initialState = {
  total: 0,
  data: [],
};

const usersSlice = createSlice({
  name: "users",
  initialState,
  reducers: {},
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder.addCase(fetchUsers.fulfilled, (state, action) => {
      state.data = action.payload;
    });
  },
});

export default usersSlice;
